### ISSUE TITLE
Header 파일 따로 구현건

### ISSUE THREAD

**Issue by rubber815** [rubber815/BabyStepSSD#18]
현재 구현기준으로 구현/선언 모두 
cpp 파일에 있으므로 refact 시 header를 분리하는 방향이 어떠신지요?

**Comment by HyunJunKwon** [comment]
https://github.com/rubber815/BabyStepSSD/pull/75
https://github.com/rubber815/BabyStepSSD/pull/77 

위 PR 을 통해 Header 가 분리된 것으로 보입니다.
