### ISSUE TITLE
Regression in 31fac719308e2447706dac5982220f138244227b

### ISSUE THREAD

**Issue by rubber815** [rubber815/BabyStepSSD#90]
![image](https://github.com/rubber815/BabyStepSSD/assets/11550024/f68a6884-1245-4efe-a7cd-f1c9c5d2d7e0)

**Comment by rubber815** [comment]
https://github.com/rubber815/BabyStepSSD/commit/31fac719308e2447706dac5982220f138244227b

**Comment by Songty93** [comment]
이슈 공유 감사합니다.
https://github.com/rubber815/BabyStepSSD/pull/92
위 PR로 Close 처리하도록 하겠습니다.
